f1_read = open('solongmichael1.mp3', 'rb')
f2_read = open('solongmichael2.mp3', 'rb')
f3_read = open('solongmichael3.mp3', 'rb')
f4_read = open('solongmichael4.mp3', 'rb')
f5_read = open('solongmichael5.mp3', 'rb')
f6_read = open('solongmichael6.mp3', 'rb')

a_write = open('So_Long_Michael_Jerry.mp3', 'wb')
a_write.write(f1_read.read())
a_write.write(f2_read.read())
a_write.write(f3_read.read())
a_write.write(f4_read.read())
a_write.write(f5_read.read())
a_write.write(f6_read.read())

f1_read.close()
f2_read.close()
f3_read.close()
f4_read.close()
f5_read.close()
f6_read.close()
a_write.flush()
a_write.close()